// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjXXNNElmYWcHzcz-v78wuhJwVx3vyNw',
    appId: '1:539935283181:web:c6a38140cd123c48fcf9e4',
    messagingSenderId: '539935283181',
    projectId: 'wallify-1c28f',
    authDomain: 'wallify-1c28f.firebaseapp.com',
    storageBucket: 'wallify-1c28f.appspot.com',
    measurementId: 'G-50XPHL2P9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlSn8Rpmr0xnGjq_jzaR7Dg8Uymhf_R3g',
    appId: '1:539935283181:android:dea17a6c3d854e4afcf9e4',
    messagingSenderId: '539935283181',
    projectId: 'wallify-1c28f',
    storageBucket: 'wallify-1c28f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzwT6dbrT-2fxRywc0igFKnvNqhPsR5w8',
    appId: '1:539935283181:ios:425c61de93d2c2acfcf9e4',
    messagingSenderId: '539935283181',
    projectId: 'wallify-1c28f',
    storageBucket: 'wallify-1c28f.appspot.com',
    iosBundleId: 'com.example.wallify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzwT6dbrT-2fxRywc0igFKnvNqhPsR5w8',
    appId: '1:539935283181:ios:425c61de93d2c2acfcf9e4',
    messagingSenderId: '539935283181',
    projectId: 'wallify-1c28f',
    storageBucket: 'wallify-1c28f.appspot.com',
    iosBundleId: 'com.example.wallify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKjXXNNElmYWcHzcz-v78wuhJwVx3vyNw',
    appId: '1:539935283181:web:3ce53bdd4c8bb8f5fcf9e4',
    messagingSenderId: '539935283181',
    projectId: 'wallify-1c28f',
    authDomain: 'wallify-1c28f.firebaseapp.com',
    storageBucket: 'wallify-1c28f.appspot.com',
    measurementId: 'G-0B9C1E3CXF',
  );
}
